name: Test, Build and Deploy

jobs:
  test:
    runs-on: ubuntu-latest
    on:
      push:
        branches:
          - master
      pull_request:
        types: [opened, synchronize, reopened]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci --silent

      - name: Run coverage test
        run: npm run test:coverage
        env:
          CI: true

      - name: Codecov
        uses: codecov/codecov-action@v1

  build-and-deploy:
    runs-on: ubuntu-latest
    on:
      push:
        branches:
          - master
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm ci --silent --only=production
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
